services:
  # web:
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/usr/src/some-api
  #   command: air cmd/main.go -b 0.0.0.0
  #   networks:
  #     - network

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - network

networks:
    network:
        driver: bridge

volumes:
    postgres-db:
        driver: local
