services:
  meuprimeirocrudgo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_USER_DB=users
      - JWT_SECRET_KEY=jwtsecrethere
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - network

networks:
  network: